import os
from pathlib import Path
BASE_DIR=Path(__file__).resolve().parent.parent
SECRET_KEY=os.environ.get("DJANGO_SECRET_KEY","dev-only-change-me");DEBUG=os.environ.get("DJANGO_DEBUG","0")=="1";ALLOWED_HOSTS=os.environ.get("DJANGO_ALLOWED_HOSTS","localhost,127.0.0.1").split(",")
INSTALLED_APPS=["django.contrib.admin","django.contrib.auth","django.contrib.contenttypes","django.contrib.sessions","django.contrib.messages","django.contrib.staticfiles","accounts","transactions","transfers","attachments","audit","reports"]
MIDDLEWARE=["django.middleware.security.SecurityMiddleware","whitenoise.middleware.WhiteNoiseMiddleware","django.contrib.sessions.middleware.SessionMiddleware","django.middleware.common.CommonMiddleware","django.middleware.csrf.CsrfViewMiddleware","django.contrib.auth.middleware.AuthenticationMiddleware","accounts.middleware.ForcePasswordChangeMiddleware","django.contrib.messages.middleware.MessageMiddleware","django.middleware.clickjacking.XFrameOptionsMiddleware"]
ROOT_URLCONF="config.urls";TEMPLATES=[{"BACKEND":"django.template.backends.django.DjangoTemplates","DIRS":[BASE_DIR/"templates"],"APP_DIRS":True,"OPTIONS":{"context_processors":["django.template.context_processors.request","django.contrib.auth.context_processors.auth","django.contrib.messages.context_processors.messages"]}}];WSGI_APPLICATION="config.wsgi.application"
DATABASES={"default":{"ENGINE":"django.db.backends.sqlite3","NAME":BASE_DIR/"test.sqlite3"}} if os.environ.get("USE_SQLITE_FOR_TESTS")=="1" else {"default":{"ENGINE":"django.db.backends.postgresql","NAME":os.environ.get("POSTGRES_DB","morasalat"),"USER":os.environ.get("POSTGRES_USER","morasalat"),"PASSWORD":os.environ.get("POSTGRES_PASSWORD",""),"HOST":os.environ.get("POSTGRES_HOST","127.0.0.1"),"PORT":os.environ.get("POSTGRES_PORT","5432"),"CONN_MAX_AGE":60}}
AUTH_USER_MODEL="accounts.User";AUTH_PASSWORD_VALIDATORS=[{"NAME":"django.contrib.auth.password_validation.MinimumLengthValidator"},{"NAME":"django.contrib.auth.password_validation.CommonPasswordValidator"}];LANGUAGE_CODE="ar";TIME_ZONE="Asia/Riyadh";USE_I18N=True;USE_TZ=True;STATIC_URL="/static/";STATIC_ROOT=BASE_DIR/"staticfiles";MEDIA_ROOT=Path(os.environ.get("MEDIA_ROOT",BASE_DIR.parent/"private_uploads"));DEFAULT_AUTO_FIELD="django.db.models.BigAutoField";SESSION_COOKIE_SECURE=not DEBUG;CSRF_COOKIE_SECURE=not DEBUG;SESSION_COOKIE_HTTPONLY=True;SESSION_COOKIE_SAMESITE="Lax";CSRF_COOKIE_SAMESITE="Lax";X_FRAME_OPTIONS="DENY";LOGIN_URL="login";LOGIN_REDIRECT_URL="dashboard";LOGOUT_REDIRECT_URL="login"
