const transactions=[
{id:'و-1448-0187',type:'وارد',subject:'دعوة للمشاركة في معرض رداء',entity:'جمعية الزاد للخدمات الإنسانية',dept:'الإدارة التنفيذية',date:'08 سبتمبر 2026',status:'متأخرة',sla:'متأخرة يومين',reason:'بانتظار اعتماد الرد من المدير التنفيذي',events:[['استلام المعاملة','مكتب الاتصالات الإدارية','08 سبتمبر، 09:14'],['تسجيل وفرز','صُنفت: دعوات وشراكات','08 سبتمبر، 09:22'],['إحالة للإدارة التنفيذية','استلمها محمد العتيبي','08 سبتمبر، 10:05'],['إعداد مسودة الرد','بانتظار الاعتماد','09 سبتمبر، 13:40']]},
{id:'و-1448-0182',type:'وارد',subject:'طلب بيانات المستفيدين للربع الثالث',entity:'وزارة الموارد البشرية',dept:'خدمات المستفيدين',date:'07 سبتمبر 2026',status:'قيد الإجراء',sla:'متبقي يوم',events:[['استلام المعاملة','البريد الرسمي','07 سبتمبر، 11:04'],['التحقق من الطلب','مكتب المدير التنفيذي','07 سبتمبر، 12:20'],['إحالة للإدارة المختصة','خدمات المستفيدين','08 سبتمبر، 08:15']]},
{id:'ص-1448-0096',type:'صادر',subject:'تقرير إنجاز مشروع السلة الغذائية',entity:'مؤسسة مانحة',dept:'الشراكات',date:'06 سبتمبر 2026',status:'متأخرة',sla:'متأخرة 4 أيام',reason:'نقص مرفق التقرير المالي',events:[['إنشاء المسودة','إدارة الشراكات','04 سبتمبر، 10:10'],['مراجعة المحتوى','مكتب المدير التنفيذي','05 سبتمبر، 14:25'],['إعادة لاستكمال المرفقات','بانتظار التقرير المالي','06 سبتمبر، 09:00']]},
{id:'و-1448-0179',type:'وارد',subject:'استفسار بشأن تجديد اتفاقية الشراكة',entity:'شركة وطنية',dept:'الشراكات',date:'05 سبتمبر 2026',status:'قيد الإجراء',sla:'متبقي يومان',events:[['استلام المعاملة','مكتب الاتصالات','05 سبتمبر، 12:11'],['إحالة للشراكات','استلمها خالد السالم','05 سبتمبر، 13:02']]},
{id:'ص-1448-0093',type:'صادر',subject:'خطاب شكر وتقدير',entity:'جامعة الراجحي',dept:'الإدارة التنفيذية',date:'03 سبتمبر 2026',status:'مكتملة',sla:'أنجزت خلال يوم',events:[['إنشاء الخطاب','أمين السر','03 سبتمبر، 09:10'],['الاعتماد والتوقيع','المدير التنفيذي','03 سبتمبر، 11:30'],['الإرسال','تم التسليم إلكترونيًا','03 سبتمبر، 11:45']]},
{id:'و-1448-0174',type:'وارد',subject:'تحديث بيانات الترخيص السنوي',entity:'المركز الوطني',dept:'الموارد المالية',date:'02 سبتمبر 2026',status:'مكتملة',sla:'أنجزت خلال 3 أيام',events:[['استلام وتسجيل','مكتب الاتصالات','02 سبتمبر، 08:30'],['استكمال البيانات','الموارد المالية','03 سبتمبر، 14:20'],['الإغلاق','تم رفع المتطلبات','05 سبتمبر، 10:00']]}
];
const statusClass=s=>s==='متأخرة'?'late':s==='مكتملة'?'done':'progress';
const row=t=>`<tr><td class="trx-id">${t.id}</td><td>${t.type}</td><td><strong>${t.subject}</strong></td><td>${t.entity}</td><td>${t.dept}</td><td><span class="badge ${statusClass(t.status)}">${t.status}</span></td><td>${t.sla}</td><td><button class="row-btn" data-id="${t.id}">←</button></td></tr>`;
function render(list=transactions){document.querySelector('#allRows').innerHTML=list.map(row).join('');document.querySelector('#urgentRows').innerHTML=list.filter(t=>t.status!=='مكتملة').slice(0,4).map(t=>`<tr><td class="trx-id">${t.id}</td><td><strong>${t.subject}</strong><small>${t.entity}</small></td><td>${t.dept}</td><td>${t.date}</td><td><span class="badge ${statusClass(t.status)}">${t.status}</span></td><td>${t.sla}</td><td><button class="row-btn" data-id="${t.id}">←</button></td></tr>`).join('');bindRows()}
function bindRows(){document.querySelectorAll('.row-btn').forEach(b=>b.onclick=()=>openDrawer(transactions.find(t=>t.id===b.dataset.id)))}
function openDrawer(t){document.querySelector('#drawerTitle').textContent=`${t.id} — ${t.subject}`;document.querySelector('#drawerBody').innerHTML=`<div class="detail-meta"><div class="meta-box"><small>الجهة</small><strong>${t.entity}</strong></div><div class="meta-box"><small>الإدارة الحالية</small><strong>${t.dept}</strong></div><div class="meta-box"><small>الحالة</small><span class="badge ${statusClass(t.status)}">${t.status}</span></div><div class="meta-box"><small>مهلة الاستجابة</small><strong>${t.sla}</strong></div></div>${t.reason?`<div class="delay-note"><strong>سبب التعطيل:</strong> ${t.reason}</div>`:''}<h3>خريطة التتبع</h3><div class="timeline">${t.events.map((e,i)=>`<div class="event ${i===t.events.length-1?'current':''}"><h4>${e[0]}</h4><p>${e[1]}</p><time>${e[2]}</time></div>`).join('')}</div><div class="modal-actions"><button class="primary">تحويل المعاملة</button><button class="outline">إضافة ملاحظة</button><button class="outline">تنزيل المرفقات</button></div>`;document.querySelector('#drawer').classList.add('open');document.querySelector('#backdrop').classList.add('open')}
function closeDrawer(){document.querySelector('#drawer').classList.remove('open');document.querySelector('#backdrop').classList.remove('open')}
const views=document.querySelectorAll('.view');function showView(id){views.forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));const n=document.querySelector(`[data-view="${id}"]`);document.querySelector('#pageTitle').textContent=n?n.textContent.replace(/[0-9⌂⇄↓↑▥▤⚙]/g,'').trim():id;document.querySelector('.sidebar').classList.remove('open')}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-open-view]').forEach(b=>b.onclick=()=>showView(b.dataset.openView));
document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');document.querySelector('#closeDrawer').onclick=closeDrawer;document.querySelector('#backdrop').onclick=closeDrawer;
document.querySelector('#newBtn').onclick=()=>document.querySelector('#newDialog').showModal();document.querySelector('#saveNew').onclick=()=>{setTimeout(()=>{const x=document.querySelector('#toast');x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)},100)};
document.querySelector('#filterBtn').onclick=()=>document.querySelector('#filterPanel').classList.toggle('open');
document.querySelector('#showLate').onclick=()=>{showView('transactions');filter('late')};document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter(b.dataset.filter)});
function filter(kind){let list=transactions;if(kind==='incoming')list=list.filter(t=>t.type==='وارد');if(kind==='outgoing')list=list.filter(t=>t.type==='صادر');if(kind==='late')list=list.filter(t=>t.status==='متأخرة');render(list)}
function applyFilters(){let list=transactions;const d=document.querySelector('#deptFilter').value,s=document.querySelector('#statusFilter').value;if(d!=='all')list=list.filter(t=>t.dept===d);if(s!=='all')list=list.filter(t=>t.status===s);render(list)}document.querySelector('#deptFilter').onchange=applyFilters;document.querySelector('#statusFilter').onchange=applyFilters;document.querySelector('#resetFilters').onclick=()=>{document.querySelector('#deptFilter').value='all';document.querySelector('#statusFilter').value='all';render()};
document.querySelector('#globalSearch').oninput=e=>{const q=e.target.value.trim();if(!q)return render();showView('transactions');render(transactions.filter(t=>Object.values(t).some(v=>typeof v==='string'&&v.includes(q))))};
const vals=[[118,72],[126,80],[109,78],[139,87],[132,91],[148,96]],months=['أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر'];document.querySelector('#chart').innerHTML=vals.map((v,i)=>`<div class="bar-group"><div class="bar in" style="height:${v[0]/1.6}px" title="وارد ${v[0]}"></div><div class="bar out" style="height:${v[1]/1.6}px" title="صادر ${v[1]}"></div><small>${months[i]}</small></div>`).join('');
const ps=[['الإدارة التنفيذية',94],['خدمات المستفيدين',88],['الموارد المالية',82],['الشراكات',76]];document.querySelector('#progressList').innerHTML=ps.map(p=>`<div class="progress-item"><div class="progress-title"><span>${p[0]}</span><b>${p[1]}%</b></div><div class="track"><div class="fill ${p[1]>85?'good':''}" style="width:${p[1]}%"></div></div></div>`).join('');
const d=new Date();document.querySelector('#today').textContent=new Intl.DateTimeFormat('ar-SA',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(d);render();
