# Generated by Django 5.2.7 on 2026-09-10 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=1)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'kind'), name='unique_counter_year_kind')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('ص', 'صادر'), ('و', 'وارد'), ('د', 'داخلي')], max_length=1)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('subject', models.CharField(max_length=400)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('external_date', models.DateField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('identity_number', models.CharField(blank=True, max_length=10)),
                ('confidentiality', models.CharField(choices=[('normal', 'عادي'), ('secret', 'سري'), ('top_secret', 'سري جدًا')], default='normal', max_length=20)),
                ('priority', models.CharField(default='عادية', max_length=20)),
                ('status', models.CharField(choices=[('routing', 'قيد التحويل'), ('processing', 'قيد التنفيذ'), ('done', 'منجزة'), ('late', 'متأخرة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], default='routing', max_length=20)),
                ('keywords', models.CharField(blank=True, max_length=400)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.department')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.entity')),
                ('linked_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.department')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.department')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='transactions.transaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
